name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.5.0
      with:
        ftp-server: ${{ secrets.HOST }}
        ftp-username: ${{ secrets.NAME }}
        ftp-password: ${{ secrets.PASS }}
        local-dir: ./  # каталог, що ви хочете завантажити
        server-dir: /www/test_git  # віддалений каталог, куди хочете завантажити файли
